<a href="https://colab.research.google.com/github/carlke2/movie_recommender/blob/main/movie_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Movie Recommendation System

This notebook builds a basic movie recommendation system using Python, pandas, and MovieLens data.

The goal is to learn how recommendation systems work step by step.

In [ ]:
print("movie recomendation notebook is ready")

movie recomendation notebook is ready

In [ ]:
import pandas as pd
import numpy as np
print("notebook is ready")

notebook is ready

In [ ]:
!wget -q https://files.grouplens.org/datasets/movielens/ml-latest-small.zip

print("Dataset zip file downloaded")

Dataset zip file downloaded

In [ ]:
!unzip -q -o ml-latest-small.zip

print("Dataset extracted successfully")

Dataset extracted successfully

In [ ]:
!ls ml-latest-small

links.csv  movies.csv  ratings.csv  README.txt	tags.csv

In [ ]:
movies = pd.read_csv("ml-latest-small/movies.csv")
ratings = pd.read_csv("ml-latest-small/ratings.csv")

print("movies loaded", movies.shape)
print("ratings loaded",ratings.shape)

movies loaded (9742, 3)
ratings loaded (100836, 4)

In [ ]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [ ]:
print("number of movies:", movies["movieId"].nunique())
print("number of users:", ratings["userId"].nunique())
print("number of ratings:", len(ratings))

number of movies: 9742
number of users: 610
number of ratings: 100836

In [ ]:
movies[movies["title"].str.contains("Matrix", case=False, na=False)]

,movieId,title,genres
1939,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller
4351,6365,"Matrix Reloaded, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX
4639,6934,"Matrix Revolutions, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX
5669,27660,"Animatrix, The (2003)",Action|Animation|Drama|Sci-Fi

In [ ]:
def search_movies(keyword):
    results = movies[movies["title"].str.contains(keyword, case=False, na=False)]
    return results[["movieId", "title", "genres"]].head(20)

In [ ]:
search_movies("Batman")

,movieId,title,genres
126,153,Batman Forever (1995),Action|Adventure|Comedy|Crime
509,592,Batman (1989),Action|Crime|Thriller
1060,1377,Batman Returns (1992),Action|Crime
1174,1562,Batman & Robin (1997),Action|Adventure|Fantasy|Thriller
2418,3213,Batman: Mask of the Phantasm (1993),Animation|Children
5463,26152,Batman (1966),Action|Adventure|Comedy
5620,27155,"Batman/Superman Movie, The (1998)",Action|Adventure|Animation|Children|Fantasy|Sc...
5631,27311,Batman Beyond: Return of the Joker (2000),Action|Animation|Crime|Sci-Fi|Thriller
5917,33794,Batman Begins (2005),Action|Crime|IMAX
6815,60979,Batman: Gotham Knight (2008),Action|Animation|Crime
7380,79274,Batman: Under the Red Hood (2010),Action|Animation
7731,90603,Batman: Year One (2011),Action|Animation|Crime
7903,95149,Superman/Batman: Public Enemies (2009),Action|Animation|Fantasy
8032,98124,"Batman: The Dark Knight Returns, Part 1 (2012)",Action|Animation|Sci-Fi
8080,99813,"Batman: The Dark Knight Returns, Part 2 (2013)",Action|Animation
8195,103233,LEGO Batman: The Movie - DC Heroes Unite (2013),Action|Adventure|Animation
8234,104141,Batman: Mystery of the Batwoman (2003),Action|Animation|Children|Crime
8486,113278,Batman: Assault on Arkham (2014),Action|Animation|Crime|Thriller
8829,131739,Batman vs. Robin (2015),Action|Adventure|Animation
8963,136864,Batman v Superman: Dawn of Justice (2016),Action|Adventure|Fantasy|Sci-Fi

In [ ]:
search_movies("Avengers")

,movieId,title,genres
1611,2153,"Avengers, The (1998)",Action|Adventure
6148,44020,Ultimate Avengers (2006),Action|Animation|Children|Sci-Fi
7693,89745,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX
8551,115727,Crippled Avengers (Can que) (Return of the 5 D...,Action|Adventure
8686,122892,Avengers: Age of Ultron (2015),Action|Adventure|Sci-Fi
8693,122912,Avengers: Infinity War - Part I (2018),Action|Adventure|Sci-Fi
9153,147657,Masked Avengers (1981),Action
9488,170297,Ultimate Avengers 2 (2006),Action|Animation|Sci-Fi

In [ ]:
search_movies("Spider")

,movieId,title,genres
3027,4051,Horrors of Spider Island (Ein Toter Hing im Ne...,Horror|Sci-Fi
3151,4238,Along Came a Spider (2001),Action|Crime|Mystery|Thriller
3819,5349,Spider-Man (2002),Action|Adventure|Sci-Fi|Thriller
3821,5356,"Giant Spider Invasion, The (1975)",Horror|Sci-Fi
4250,6197,Spider (2002),Drama|Mystery
4567,6786,Kiss of the Spider Woman (1985),Drama
5260,8636,Spider-Man 2 (2004),Action|Adventure|Sci-Fi|IMAX
6470,52722,Spider-Man 3 (2007),Action|Adventure|Sci-Fi|Thriller|IMAX
6685,58105,"Spiderwick Chronicles, The (2008)",Adventure|Children|Drama|Fantasy|IMAX
7927,95510,"Amazing Spider-Man, The (2012)",Action|Adventure|Sci-Fi|IMAX
8406,110553,The Amazing Spider-Man 2 (2014),Action|Sci-Fi|IMAX
8699,122926,Untitled Spider-Man Reboot (2017),Action|Adventure|Fantasy

In [ ]:
my_ratings = {
    "Matrix, The (1999)": 5,
    "Dark Knight, The (2008)": 5,
    "Iron Man (2008)": 4,
    "Avengers, The (2012)": 4,
    "Toy Story (1995)": 2
}

my_ratings

{'Matrix, The (1999)': 5,
 'Dark Knight, The (2008)': 5,
 'Iron Man (2008)': 4,
 'Avengers, The (2012)': 4,
 'Toy Story (1995)': 2}

In [ ]:
rated_movies = movies[movies["title"].isin(my_ratings.keys())]

rated_movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1939,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller
6710,58559,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
6743,59315,Iron Man (2008),Action|Adventure|Sci-Fi
7693,89745,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX

In [ ]:
rated_movies = rated_movies.copy()

rated_movies["my_rating"] = rated_movies["title"].map(my_ratings)

rated_movies

,movieId,title,genres,my_rating
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,2
1939,2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller,5
6710,58559,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,5
6743,59315,Iron Man (2008),Action|Adventure|Sci-Fi,4
7693,89745,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX,4

In [ ]:
movies_clean = movies.copy()

movies_clean["genres_clean"] = movies_clean["genres"].str.replace("|", " ", regex=False)

movies_clean[["title", "genres", "genres_clean"]].head()

,title,genres,genres_clean
0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Adventure Animation Children Comedy Fantasy
1,Jumanji (1995),Adventure|Children|Fantasy,Adventure Children Fantasy
2,Grumpier Old Men (1995),Comedy|Romance,Comedy Romance
3,Waiting to Exhale (1995),Comedy|Drama|Romance,Comedy Drama Romance
4,Father of the Bride Part II (1995),Comedy,Comedy

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

print("Text vectorizer imported")

Text vectorizer imported

In [ ]:
vectorizer = TfidfVectorizer()

genre_matrix = vectorizer.fit_transform(movies_clean["genres_clean"])

print("Genre matrix created successfully")
print("Shape:", genre_matrix.shape)

Genre matrix created successfully
Shape: (9742, 24)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

print("Similarity tool imported")

Similarity tool imported

In [ ]:
liked_profile = np.zeros(genre_matrix.shape[1])

for movie_index, rating in zip(rated_movies.index, rated_movies["my_rating"]):
    liked_profile += genre_matrix[movie_index].toarray()[0] * rating

print("Taste profile created")
print("Profile shape:", liked_profile.shape)

Taste profile created
Profile shape: (24,)

In [ ]:
similarity_scores = cosine_similarity([liked_profile], genre_matrix).flatten()

movies_clean["recommendation_score"] = similarity_scores

movies_clean[["title", "genres", "recommendation_score"]].sort_values(
    by="recommendation_score",
    ascending=False
).head(10)

,title,genres,recommendation_score
4351,"Matrix Reloaded, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
8120,G.I. Joe: Retaliation (2013),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
4639,"Matrix Revolutions, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
6470,Spider-Man 3 (2007),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
7324,Iron Man 2 (2010),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
8426,Godzilla (2014),Action|Adventure|Sci-Fi|IMAX,0.924965
6238,Superman Returns (2006),Action|Adventure|Sci-Fi|IMAX,0.924965
3832,Star Wars: Episode II - Attack of the Clones (...,Action|Adventure|Sci-Fi|IMAX,0.924965
7927,"Amazing Spider-Man, The (2012)",Action|Adventure|Sci-Fi|IMAX,0.924965
8159,Star Trek Into Darkness (2013),Action|Adventure|Sci-Fi|IMAX,0.924965

In [ ]:
already_rated_titles = list(my_ratings.keys())

recommendations = movies_clean[
    ~movies_clean["title"].isin(already_rated_titles)
].sort_values(
    by="recommendation_score",
    ascending=False
)

recommendations[["title", "genres", "recommendation_score"]].head(20)

,title,genres,recommendation_score
7324,Iron Man 2 (2010),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
4351,"Matrix Reloaded, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
4639,"Matrix Revolutions, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
8120,G.I. Joe: Retaliation (2013),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
6470,Spider-Man 3 (2007),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
7842,John Carter (2012),Action|Adventure|Sci-Fi|IMAX,0.924965
7927,"Amazing Spider-Man, The (2012)",Action|Adventure|Sci-Fi|IMAX,0.924965
7018,Star Trek (2009),Action|Adventure|Sci-Fi|IMAX,0.924965
7064,Transformers: Revenge of the Fallen (2009),Action|Adventure|Sci-Fi|IMAX,0.924965
7212,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,0.924965
8159,Star Trek Into Darkness (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8137,Oblivion (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8194,Pacific Rim (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8178,After Earth (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8295,The Hunger Games: Catching Fire (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8287,Ender's Game (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8426,Godzilla (2014),Action|Adventure|Sci-Fi|IMAX,0.924965
8395,Captain America: The Winter Soldier (2014),Action|Adventure|Sci-Fi|IMAX,0.924965
7484,Tron: Legacy (2010),Action|Adventure|Sci-Fi|IMAX,0.924965
6238,Superman Returns (2006),Action|Adventure|Sci-Fi|IMAX,0.924965

In [ ]:
def recommend_movies(my_ratings, top_n=20):
    rated_movies = movies_clean[movies_clean["title"].isin(my_ratings.keys())].copy()

    if rated_movies.empty:
        return "No matching movies found. Use search_movies() to check exact titles."

    rated_movies["my_rating"] = rated_movies["title"].map(my_ratings)

    liked_profile = np.zeros(genre_matrix.shape[1])

    for movie_index, rating in zip(rated_movies.index, rated_movies["my_rating"]):
        liked_profile += genre_matrix[movie_index].toarray()[0] * rating

    similarity_scores = cosine_similarity([liked_profile], genre_matrix).flatten()

    results = movies_clean.copy()
    results["recommendation_score"] = similarity_scores

    already_rated_titles = list(my_ratings.keys())

    recommendations = results[
        ~results["title"].isin(already_rated_titles)
    ].sort_values(
        by="recommendation_score",
        ascending=False
    )

    return recommendations[["title", "genres", "recommendation_score"]].head(top_n)

In [ ]:
recommend_movies(my_ratings, top_n=55)

,title,genres,recommendation_score
7324,Iron Man 2 (2010),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
4351,"Matrix Reloaded, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
4639,"Matrix Revolutions, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
8120,G.I. Joe: Retaliation (2013),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
6470,Spider-Man 3 (2007),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954
7842,John Carter (2012),Action|Adventure|Sci-Fi|IMAX,0.924965
7927,"Amazing Spider-Man, The (2012)",Action|Adventure|Sci-Fi|IMAX,0.924965
7018,Star Trek (2009),Action|Adventure|Sci-Fi|IMAX,0.924965
7064,Transformers: Revenge of the Fallen (2009),Action|Adventure|Sci-Fi|IMAX,0.924965
7212,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,0.924965
8159,Star Trek Into Darkness (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8137,Oblivion (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8194,Pacific Rim (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8178,After Earth (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8295,The Hunger Games: Catching Fire (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8287,Ender's Game (2013),Action|Adventure|Sci-Fi|IMAX,0.924965
8426,Godzilla (2014),Action|Adventure|Sci-Fi|IMAX,0.924965
8395,Captain America: The Winter Soldier (2014),Action|Adventure|Sci-Fi|IMAX,0.924965
7484,Tron: Legacy (2010),Action|Adventure|Sci-Fi|IMAX,0.924965
6238,Superman Returns (2006),Action|Adventure|Sci-Fi|IMAX,0.924965
3832,Star Wars: Episode II - Attack of the Clones (...,Action|Adventure|Sci-Fi|IMAX,0.924965
5260,Spider-Man 2 (2004),Action|Adventure|Sci-Fi|IMAX,0.924965
7820,Journey 2: The Mysterious Island (2012),Action|Adventure|Comedy|Sci-Fi|IMAX,0.907394
8406,The Amazing Spider-Man 2 (2014),Action|Sci-Fi|IMAX,0.877935
8438,Edge of Tomorrow (2014),Action|Sci-Fi|IMAX,0.877935
8252,Gravity (2013),Action|Sci-Fi|IMAX,0.877935
8151,Iron Man 3 (2013),Action|Sci-Fi|Thriller|IMAX,0.877923
7866,Battleship (2012),Action|Sci-Fi|Thriller|IMAX,0.877923
7545,I Am Number Four (2011),Action|Sci-Fi|Thriller|IMAX,0.877923
8238,Riddick (2013),Action|Sci-Fi|Thriller|IMAX,0.877923
6151,V for Vendetta (2006),Action|Sci-Fi|Thriller|IMAX,0.877923
6521,Transformers (2007),Action|Sci-Fi|Thriller|IMAX,0.877923
8199,Elysium (2013),Action|Drama|Sci-Fi|IMAX,0.874635
7710,Real Steel (2011),Action|Drama|Sci-Fi|IMAX,0.874635
8683,Star Wars: Episode VII - The Force Awakens (2015),Action|Adventure|Fantasy|Sci-Fi|IMAX,0.873461
8183,Man of Steel (2013),Action|Adventure|Fantasy|Sci-Fi|IMAX,0.873461
8358,RoboCop (2014),Action|Crime|Sci-Fi|IMAX,0.870521
7883,Men in Black III (M.III.B.) (M.I.B.³) (2012),Action|Comedy|Sci-Fi|IMAX,0.858371
8228,3 dev adam (Three Giant Men) (1973),Action|Adventure|Sci-Fi,0.841563
4306,Bulletproof Monk (2003),Action|Adventure|Sci-Fi,0.841563
9557,Valerian and the City of a Thousand Planets (2...,Action|Adventure|Sci-Fi,0.841563
4422,Hulk (2003),Action|Adventure|Sci-Fi,0.841563
1346,Lost in Space (1998),Action|Adventure|Sci-Fi,0.841563
1058,Star Trek III: The Search for Spock (1984),Action|Adventure|Sci-Fi,0.841563
2889,Godzilla 2000 (Gojira ni-sen mireniamu) (1999),Action|Adventure|Sci-Fi,0.841563
2836,X-Men (2000),Action|Adventure|Sci-Fi,0.841563
898,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,0.841563
4619,Returner (Ritaanaa) (2002),Action|Adventure|Sci-Fi,0.841563
4658,Timeline (2003),Action|Adventure|Sci-Fi,0.841563
6825,Mutant Chronicles (2008),Action|Adventure|Sci-Fi,0.841563
6863,"20,000 Leagues Under the Sea (1916)",Action|Adventure|Sci-Fi,0.841563
6894,Farscape: The Peacekeeper Wars (2004),Action|Adventure|Sci-Fi,0.841563
6963,Outlander (2008),Action|Adventure|Sci-Fi,0.841563
3632,Spacehunter: Adventures in the Forbidden Zone ...,Action|Adventure|Sci-Fi,0.841563
176,Waterworld (1995),Action|Adventure|Sci-Fi,0.841563

In [ ]:
movie_stats = ratings.groupby("movieId").agg(
    average_rating=("rating", "mean"),
    rating_count=("rating", "count")
).reset_index()

movie_stats.head()

   movieId  average_rating  rating_count
0        1        3.920930           215
1        2        3.431818           110
2        3        3.259615            52
3        4        2.357143             7
4        5        3.071429            49

In [ ]:
movies_clean = movies_clean.merge(movie_stats, on="movieId", how="left")

movies_clean[["movieId", "title", "genres", "average_rating", "rating_count"]].head()

,movieId,title,genres,average_rating,rating_count
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.920930,215.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.431818,110.0
2,3,Grumpier Old Men (1995),Comedy|Romance,3.259615,52.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.357143,7.0
4,5,Father of the Bride Part II (1995),Comedy,3.071429,49.0

In [ ]:
movies_clean["average_rating"] = movies_clean["average_rating"].fillna(0)
movies_clean["rating_count"] = movies_clean["rating_count"].fillna(0)

movies_clean[["title", "average_rating", "rating_count"]].head()

                                title  average_rating  rating_count
0                    Toy Story (1995)        3.920930         215.0
1                      Jumanji (1995)        3.431818         110.0
2             Grumpier Old Men (1995)        3.259615          52.0
3            Waiting to Exhale (1995)        2.357143           7.0
4  Father of the Bride Part II (1995)        3.071429          49.0

In [ ]:
movies_clean["public_rating_score"] = movies_clean["average_rating"] / 5

movies_clean["popularity_score"] = np.log1p(movies_clean["rating_count"])
movies_clean["popularity_score"] = movies_clean["popularity_score"] / movies_clean["popularity_score"].max()

movies_clean[[
    "title",
    "average_rating",
    "rating_count",
    "public_rating_score",
    "popularity_score"
]].head()

,title,average_rating,rating_count,public_rating_score,popularity_score
0,Toy Story (1995),3.920930,215.0,0.784186,0.926917
1,Jumanji (1995),3.431818,110.0,0.686364,0.812115
2,Grumpier Old Men (1995),3.259615,52.0,0.651923,0.684640
3,Waiting to Exhale (1995),2.357143,7.0,0.471429,0.358580
4,Father of the Bride Part II (1995),3.071429,49.0,0.614286,0.674592

In [ ]:
movies_clean["final_score"] = (
    movies_clean["recommendation_score"] * 0.70 +
    movies_clean["public_rating_score"] * 0.20 +
    movies_clean["popularity_score"] * 0.10
)

movies_clean[[
    "title",
    "genres",
    "recommendation_score",
    "average_rating",
    "rating_count",
    "final_score"
]].sort_values(
    by="final_score",
    ascending=False
).head(20)

,title,genres,recommendation_score,average_rating,rating_count,final_score
7693,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX,0.924965,3.869565,69.0,0.875520
5260,Spider-Man 2 (2004),Action|Adventure|Sci-Fi|IMAX,0.924965,3.803797,79.0,0.875192
7018,Star Trek (2009),Action|Adventure|Sci-Fi|IMAX,0.924965,3.864407,59.0,0.872655
7212,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,0.924965,3.603093,97.0,0.870663
4351,"Matrix Reloaded, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.354167,96.0,0.861221
8395,Captain America: The Winter Soldier (2014),Action|Adventure|Sci-Fi|IMAX,0.924965,3.741935,31.0,0.856917
7324,Iron Man 2 (2010),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.510638,47.0,0.855348
224,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,0.841563,4.231076,251.0,0.853687
8159,Star Trek Into Darkness (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.685185,27.0,0.852344
3832,Star Wars: Episode II - Attack of the Clones (...,Action|Adventure|Sci-Fi|IMAX,0.924965,3.157609,92.0,0.851941
898,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,0.841563,4.215640,211.0,0.850089
4639,"Matrix Revolutions, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.151899,79.0,0.849807
8295,The Hunger Games: Catching Fire (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.634615,26.0,0.849694
6151,V for Vendetta (2006),Action|Sci-Fi|Thriller|IMAX,0.877923,3.885000,100.0,0.849530
911,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,0.841563,4.137755,196.0,0.845708
8438,Edge of Tomorrow (2014),Action|Sci-Fi|IMAX,0.877935,3.977273,44.0,0.839288
8194,Pacific Rim (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.607143,14.0,0.838459
7927,"Amazing Spider-Man, The (2012)",Action|Adventure|Sci-Fi|IMAX,0.924965,3.250000,30.0,0.836692
8287,Ender's Game (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.437500,16.0,0.833832
6470,Spider-Man 3 (2007),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.000000,44.0,0.833810

In [ ]:
already_rated_titles = list(my_ratings.keys())

final_recommendations = movies_clean[
    ~movies_clean["title"].isin(already_rated_titles)
].sort_values(
    by="final_score",
    ascending=False
)

final_recommendations[[
    "title",
    "genres",
    "recommendation_score",
    "average_rating",
    "rating_count",
    "final_score"
]].head(20)

,title,genres,recommendation_score,average_rating,rating_count,final_score
5260,Spider-Man 2 (2004),Action|Adventure|Sci-Fi|IMAX,0.924965,3.803797,79.0,0.875192
7018,Star Trek (2009),Action|Adventure|Sci-Fi|IMAX,0.924965,3.864407,59.0,0.872655
7212,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,0.924965,3.603093,97.0,0.870663
4351,"Matrix Reloaded, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.354167,96.0,0.861221
8395,Captain America: The Winter Soldier (2014),Action|Adventure|Sci-Fi|IMAX,0.924965,3.741935,31.0,0.856917
7324,Iron Man 2 (2010),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.510638,47.0,0.855348
224,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,0.841563,4.231076,251.0,0.853687
8159,Star Trek Into Darkness (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.685185,27.0,0.852344
3832,Star Wars: Episode II - Attack of the Clones (...,Action|Adventure|Sci-Fi|IMAX,0.924965,3.157609,92.0,0.851941
898,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,0.841563,4.215640,211.0,0.850089
4639,"Matrix Revolutions, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.151899,79.0,0.849807
8295,The Hunger Games: Catching Fire (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.634615,26.0,0.849694
6151,V for Vendetta (2006),Action|Sci-Fi|Thriller|IMAX,0.877923,3.885000,100.0,0.849530
911,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,0.841563,4.137755,196.0,0.845708
8438,Edge of Tomorrow (2014),Action|Sci-Fi|IMAX,0.877935,3.977273,44.0,0.839288
8194,Pacific Rim (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.607143,14.0,0.838459
7927,"Amazing Spider-Man, The (2012)",Action|Adventure|Sci-Fi|IMAX,0.924965,3.250000,30.0,0.836692
8287,Ender's Game (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.437500,16.0,0.833832
6470,Spider-Man 3 (2007),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.000000,44.0,0.833810
8137,Oblivion (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.300000,20.0,0.831976

In [ ]:
def recommend_movies_v2(my_ratings, top_n=20):
    rated_movies = movies_clean[movies_clean["title"].isin(my_ratings.keys())].copy()

    if rated_movies.empty:
        return "No matching movies found. Use search_movies() to check exact titles."

    rated_movies["my_rating"] = rated_movies["title"].map(my_ratings)

    liked_profile = np.zeros(genre_matrix.shape[1])

    for movie_index, rating in zip(rated_movies.index, rated_movies["my_rating"]):
        liked_profile += genre_matrix[movie_index].toarray()[0] * rating

    similarity_scores = cosine_similarity([liked_profile], genre_matrix).flatten()

    results = movies_clean.copy()
    results["recommendation_score"] = similarity_scores

    results["public_rating_score"] = results["average_rating"] / 5

    results["popularity_score"] = np.log1p(results["rating_count"])
    results["popularity_score"] = results["popularity_score"] / results["popularity_score"].max()

    results["final_score"] = (
        results["recommendation_score"] * 0.70 +
        results["public_rating_score"] * 0.20 +
        results["popularity_score"] * 0.10
    )

    already_rated_titles = list(my_ratings.keys())

    recommendations = results[
        ~results["title"].isin(already_rated_titles)
    ].sort_values(
        by="final_score",
        ascending=False
    )

    return recommendations[[
        "title",
        "genres",
        "recommendation_score",
        "average_rating",
        "rating_count",
        "final_score"
    ]].head(top_n)

In [ ]:
recommend_movies_v2(my_ratings, top_n=20)

,title,genres,recommendation_score,average_rating,rating_count,final_score
5260,Spider-Man 2 (2004),Action|Adventure|Sci-Fi|IMAX,0.924965,3.803797,79.0,0.875192
7018,Star Trek (2009),Action|Adventure|Sci-Fi|IMAX,0.924965,3.864407,59.0,0.872655
7212,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,0.924965,3.603093,97.0,0.870663
4351,"Matrix Reloaded, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.354167,96.0,0.861221
8395,Captain America: The Winter Soldier (2014),Action|Adventure|Sci-Fi|IMAX,0.924965,3.741935,31.0,0.856917
7324,Iron Man 2 (2010),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.510638,47.0,0.855348
224,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,0.841563,4.231076,251.0,0.853687
8159,Star Trek Into Darkness (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.685185,27.0,0.852344
3832,Star Wars: Episode II - Attack of the Clones (...,Action|Adventure|Sci-Fi|IMAX,0.924965,3.157609,92.0,0.851941
898,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,0.841563,4.215640,211.0,0.850089
4639,"Matrix Revolutions, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.151899,79.0,0.849807
8295,The Hunger Games: Catching Fire (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.634615,26.0,0.849694
6151,V for Vendetta (2006),Action|Sci-Fi|Thriller|IMAX,0.877923,3.885000,100.0,0.849530
911,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,0.841563,4.137755,196.0,0.845708
8438,Edge of Tomorrow (2014),Action|Sci-Fi|IMAX,0.877935,3.977273,44.0,0.839288
8194,Pacific Rim (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.607143,14.0,0.838459
7927,"Amazing Spider-Man, The (2012)",Action|Adventure|Sci-Fi|IMAX,0.924965,3.250000,30.0,0.836692
8287,Ender's Game (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.437500,16.0,0.833832
6470,Spider-Man 3 (2007),Action|Adventure|Sci-Fi|Thriller|IMAX,0.925954,3.000000,44.0,0.833810
8137,Oblivion (2013),Action|Adventure|Sci-Fi|IMAX,0.924965,3.300000,20.0,0.831976

In [ ]:
clean_recommendations = recommend_movies_v2(my_ratings, top_n=20).copy()

clean_recommendations["recommendation_score"] = clean_recommendations["recommendation_score"].round(3)
clean_recommendations["average_rating"] = clean_recommendations["average_rating"].round(2)
clean_recommendations["final_score"] = clean_recommendations["final_score"].round(3)

clean_recommendations.reset_index(drop=True)

,title,genres,recommendation_score,average_rating,rating_count,final_score
0,Spider-Man 2 (2004),Action|Adventure|Sci-Fi|IMAX,0.925,3.80,79.0,0.875
1,Star Trek (2009),Action|Adventure|Sci-Fi|IMAX,0.925,3.86,59.0,0.873
2,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,0.925,3.60,97.0,0.871
3,"Matrix Reloaded, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.926,3.35,96.0,0.861
4,Captain America: The Winter Soldier (2014),Action|Adventure|Sci-Fi|IMAX,0.925,3.74,31.0,0.857
5,Iron Man 2 (2010),Action|Adventure|Sci-Fi|Thriller|IMAX,0.926,3.51,47.0,0.855
6,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi,0.842,4.23,251.0,0.854
7,Star Trek Into Darkness (2013),Action|Adventure|Sci-Fi|IMAX,0.925,3.69,27.0,0.852
8,Star Wars: Episode II - Attack of the Clones (...,Action|Adventure|Sci-Fi|IMAX,0.925,3.16,92.0,0.852
9,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi,0.842,4.22,211.0,0.850
10,"Matrix Revolutions, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,0.926,3.15,79.0,0.850
11,The Hunger Games: Catching Fire (2013),Action|Adventure|Sci-Fi|IMAX,0.925,3.63,26.0,0.850
12,V for Vendetta (2006),Action|Sci-Fi|Thriller|IMAX,0.878,3.88,100.0,0.850
13,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Sci-Fi,0.842,4.14,196.0,0.846
14,Edge of Tomorrow (2014),Action|Sci-Fi|IMAX,0.878,3.98,44.0,0.839
15,Pacific Rim (2013),Action|Adventure|Sci-Fi|IMAX,0.925,3.61,14.0,0.838
16,"Amazing Spider-Man, The (2012)",Action|Adventure|Sci-Fi|IMAX,0.925,3.25,30.0,0.837
17,Ender's Game (2013),Action|Adventure|Sci-Fi|IMAX,0.925,3.44,16.0,0.834
18,Spider-Man 3 (2007),Action|Adventure|Sci-Fi|Thriller|IMAX,0.926,3.00,44.0,0.834
19,Oblivion (2013),Action|Adventure|Sci-Fi|IMAX,0.925,3.30,20.0,0.832

In [ ]:
clean_recommendations.to_csv("my_movie_recommendations.csv", index=False)

print("Recommendations saved successfully")

Recommendations saved successfully

In [ ]:
from google.colab import files

files.download("my_movie_recommendations.csv")